name: Built PDF of pattern and instructions
on:
    push:
        branches:
          - main
        paths:
          - 'README.md'
          - 'images/**'
          - 'pattern-templates/open-liberty-logo-mugrug-fpp-template.pdf'
          # Limit triggering to commits pushed to these files only.
    workflow_dispatch:
    # Allow manual triggering.
jobs:
    converttopdf:
        name: Build PDF
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: BaileyJM02/markdown-to-pdf@v1
              with:
                  input_path: README.md
                  output_dir: pdfs/
                  images_dir: images
                  image_import: images
                  # Needs this line to know where images are for some reason.
                  build_html: false
            - uses: actions/upload-artifact@v3
              with:
                  name: pattern
                  path: pdfs
    build:
        name: CombinePDFS
        runs-on: ubuntu-latest
        needs: converttopdf
        env:
          path: pdfs
          filename: Open-Liberty-rug-mug-mini-quilt
        steps:
            - uses: actions/checkout@v2
            - uses: elMuso/MergePDFs-action@1.1
              with:
                path: ${{env.path}}
                filename: ${{env.filename}}
            - name: Upload combined pdf
              uses: actions/upload-artifact@v2
              with:
                name: ${{env.filename}}
                path: ${{env.path}}/${{env.filename}}.pdf          
            - name: List all files
              run: ls -lR
              # Check that the file has been built.
            - name: Commit built PDF to my repo
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add pdfs/README.pdf
                git commit -m "generated PDF"
                git push