name: Built PDF of pattern and instructions
on:
    push:
        branches:
          - main
        paths:
          - 'README.md'
          - 'images/**'
          - 'pattern-templates/open-liberty-logo-mugrug-fpp-template.pdf'
          # Limit triggering to commits pushed to these files only.
    workflow_dispatch:
    # Allow manual triggering.
jobs:
    converttopdf:
        name: Build PDF
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Create temp dir
              run: mkdir temp
            - uses: BaileyJM02/markdown-to-pdf@v1
              with:
                  input_path: README.md
                  output_dir: temp/
                  images_dir: images
                  image_import: images
                  # Needs this line to know where images are for some reason.
                  build_html: false
            - name: Move to temp dir and order the pdfs for merging
              run: |
                  mv temp/README.pdf temp/001.pdf
                  mv pdfs/open-liberty-logo-mugrug-fpp-template.pdf temp/002.pdf
            - uses: elMuso/MergePDFs-action@1.1
              with:
                path: temp
                filename: README-combined.pdf   
            - name: List all files
              run: ls -lR
              # Check that the file has been built.
            - name: Commit built PDF to my repo
              run: |
                mv temp/README-combined.pdf ./Open-Liberty-rug-mug-mini-quilt.pdf
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add Open-Liberty-rug-mug-mini-quilt.pdf
                git commit -m "generated PDF"
                git push