name: Built PDF of pattern and instructions
on:
    push:
        branches:
          - main
        paths:
          - 'README.md'
          - 'images/**'
          - 'pdfs/open-liberty-logo-mugrug-fpp-template.pdf'
          # Limit triggering to commits pushed to these files only.
    workflow_dispatch:
    # Allow manual triggering.
jobs:
    converttopdf:
        name: Build PDF
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: BaileyJM02/markdown-to-pdf@v1
              with:
                  input_path: README.md
                  output_dir: pdfs/
                  images_dir: images
                  image_import: images
                  # Needs this line to know where images are for some reason.
                  build_html: false
            - name: List all files
              run: ls -lR
              # Check that the file has been built.
            - name: Renamed converted PDF
              run: mv pdfs/README.pdf pdfs/open-liberty-rug-mug-mini-quilt-instructions.pdf
            - name: List all files
              run: ls -lR
              # Check that the file has been built.
            - name: Commit built PDF to my repo
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add pdfs/open-liberty-rug-mug-mini-quilt-instructions.pdf
                git commit -m "generated PDF"
                git push