name: Built PDF of pattern and instructions
on:
    push:
        branches:
          - main
        paths:
          - 'README.md'
          - 'images/**'
          - 'pattern-templates/open-liberty-logo-mugrug-fpp-template.pdf'
          # Limit triggering to commits pushed to these files only.
    workflow_dispatch:
    # Allow manual triggering.
jobs:
    converttopdf:
        name: Build PDF
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: BaileyJM02/markdown-to-pdf@v1
              with:
                  input_path: README.md
                  output_dir: pdfs/
                  images_dir: '.'
                  build_html: true
            - name: List all files
              run: ls -lR
              # Check that the file has been built.
            - name: Commit built PDF to my repo
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add pdfs/README.pdf
                git commit -m "generated PDF"
                git push
#            - uses: actions/upload-artifact@v3
#              with:
#                  name: pattern
#                  path: pdfs